package dmdd.dmddas.common.constant
{
	[Bindable]
	public class UIConst
	{			
		//	UiCode	begin
		public static var UICODE_HISTORYDATA_QUERY:String = "UICODE_HISTORYDATA_QUERY";
		public static var UICODE_HISTORYDATA_ADJUST:String = "UICODE_HISTORYDATA_ADJUST";
		public static var UICODE_HISTORYDATA_INPUT:String = "UICODE_HISTORYDATA_INPUT";
		
		public static var UICODE_FORECASTDATA_QUERY:String = "UICODE_FORECASTDATA_QUERY";
		public static var UICODE_FORECASTDATA_FORECASTHAND:String = "UICODE_FORECASTDATA_FORECASTHAND";		
		public static var UICODE_FORECASTDATA_FORECASTHANDQUICK:String = "UICODE_FORECASTDATA_FORECASTHANDQUICK";
		public static var UICODE_FORECASTDATA_AUDIT:String = "UICODE_FORECASTDATA_AUDIT";
		
		public static var UICODE_REPORT_ROW:String = "UICODE_REPORT_ROW";
		public static var UICODE_REPORT_COLUMN:String = "UICODE_REPORT_COLUMN";
		public static var UICODE_REPORT_WEIGHT:String = "UICODE_REPORT_WEIGHT";
		public static var UICODE_REPORT_STATISTICS:String = "UICODE_REPORT_STATISTICS";
		public static var UICODE_REPORT_BREAKDOWN:String = "UICODE_REPORT_BREAKDOWN";
		public static var UICODE_REPORT_EXPANSION:String = "UICODE_REPORT_EXPANSION";
		public static var UICODE_REPORT_HISTORYFORECAST:String = "UICODE_REPORT_HISTORYFORECAST";
		
		public static var UICODE_HOMEPAGE:String = "UICODE_HOMEPAGE";
		public static var UICODE_CUSTOMREPORT_AU:String = "UICODE_CUSTOMREPORT_AU";
		
		public static var UICODE_PRICEDATA_ADJUST:String = "UICODE_PRICEDATA_ADJUST";
		public static var UICODE_PRICEDATA_QUERY:String = "UICODE_PRICEDATA_QUERY";
		
		public static var UICODE_FORECAST_FORECASTASSESSMENT_CREATE_MANU:String="UICODE_FORECAST_FORECASTASSESSMENT_CREATE_MANU";
		public static var UICODE_FORECAST_FORECASTASSESSMENT_QUERY:String="UICODE_FORECAST_FORECASTASSESSMENT_QUERY";
		
		public static var UICODE_CONVERSION_CONVERSIONSET:String="UICODE_CONVERSION_CONVERSIONSET";
		
		public static var UICODE_MOBILE_REPORT_SINGLE:String = "UICODE_MOBILE_REPORT_SINGLE";
		public static var UICODE_MOBILE_REPORT_MUTLE:String = "UICODE_MOBILE_REPORT_MUTLE";
		public static var UICODE_MOBILE_FORECAST:String = "UICODE_MOBILE_FORECAST";
		
		/** SOP */
		public static var UICODE_SOP_SOPHAND:String = "UICODE_SOP_SOPHAND";
		//	UiCode	end
		
		
		// 树形结构的产品组织之间的关系     begin
		public static var RELATION_FIRST2SECOND_COVERING:String		= "RELATION_FIRST2SECOND_COVERING";		//FIRST => SECOND
		public static var RELATION_FIRST2SECOND_COVERED:String		= "RELATION_FIRST2SECOND_COVERED";		//FIRST <= SECOND
		public static var RELATION_FIRST2SECOND_EQUAL:String		= "RELATION_FIRST2SECOND_EQUAL";		//FIRST == SECOND
		public static var RELATION_FIRST2SECOND_IRRELATED:String	= "RELATION_FIRST2SECOND_IRRELATED";	//FIRST and SECOND == null
		public static var RELATION_FIRST2SECOND_INTERSECT_1:String	= "RELATION_FIRST2SECOND_INTERSECT_1";	//FIRST and SECOND != null P1>P2 O1<O2 
		public static var RELATION_FIRST2SECOND_INTERSECT_2:String	= "RELATION_FIRST2SECOND_INTERSECT_2";	//FIRST and SECOND != null P1<P2 O1>O2
		// 树形结构的产品组织之间的关系     end
								
		public function UIConst()
		{
			//TODO: implement function
		}

	}
}
